# Generated by Django 5.2.8 on 2025-11-06 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('education', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('skills', models.CharField(max_length=255)),
                ('experience', models.FloatField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('job_role', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('relocate', models.CharField(max_length=10)),
                ('referral_code', models.CharField(max_length=10, unique=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
